const actionTypes = {
  LOADING: "LOADING",
  SIGNUP: "SIGNUP",
  LOGIN: "LOGIN",
  SIGNUPFAIL: "SIGNUPFAIL",
  SIGNUPSUCCESS: "SIGNUPSUCCESS",
  FACEBOOK_LOGIN: "FACEBOOK_LOGIN",
  GOOGLE_LOGIN: "GOOGLE_LOGIN",
  GOOGLE_LOGIN_FAIL: "GOOGLE_LOGIN_FAIL",
  GOOGLE_LOGIN_SUCCESS: "GOOGLE_LOGIN_SUCCESS",
  GET_PROFILE: 'GET_PROFILE',
  UPDATE_PROFILE: 'UPDATE_PROFILE'
};
export default actionTypes;
